import streamlit as st
import pandas as pd
from pandasai import PandasAI  
import os
from pandasai.llm.openai import OpenAI

dir_path = os.getcwd()

llm = OpenAI(api_token="YOUR API KEY")
pandas_ai = PandasAI(llm, save_charts=True, save_charts_path=dir_path)

st.set_page_config(page_title="Dashboard", layout='wide', initial_sidebar_state='expanded')

st.title("Analytics Dashboard")
st.subheader("Talk to Data")
with st.sidebar:
    uploaded_file = st.file_uploader("Upload a CSV file", type="csv")

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file, encoding='Latin-1')
    st.write(df)

question = st.text_input(label='Talk to Data')

if question == '':
    st.write("Nothing to Show")
else:
    output = pandas_ai(df, question)
    if isinstance(question, str) and any(word in question.lower() for word in ["chart", "graph", "image","fig","figure","image","img", "Plot"]):
        image_path = "./exports/charts/chart.png"
        st.image(image_path, caption='Generated by AI', use_column_width=True)
    else:
        st.write(output)
   
# Plot a piechart for the top 3 most selling productline
# Show me an image for the top 4 countries with the most sales
# Can you show me the total number of counts for all the dealsize